device_type: mimxrt1170_cm7
job_name: boot
timeouts:
  job:
    minutes: 15
  action:
    minutes: 5
  connection:
    minutes: 2
priority: medium
visibility: public
metadata:
  aknano_init/RUNNING_FROM_SLOT: "1"
  aknano_init/RUNNING_VERSION: "1001"
actions:
- deploy:
    timeout:
      minutes: 15
    to: downloads
    images:
      build:
        url: {BUILD_URL}
        headers:
          Authorization: GITHUB_AUTH
      mcuboot:
        url: https://s.lava.infra.foundries.io/mcuboot_opensource.elf
        headers:
          Authorization: LAVA_BASIC_AUTH
    postprocess:
      docker:
        image: miloszwasilewski/mcu_lava:latest
        steps:
        - export IMAGE_PATH=$PWD
        - ls -l "${IMAGE_PATH}"
        - unzip "zip"
        - ls -l "${IMAGE_PATH}"
        - echo "DEVICE_TYPE=mimxrt1170_cm7" >> flash.settings
        - echo "TMPFILES=mcuboot_opensource.elf" >> flash.settings
        - imgtool sign --key /home/root-rsa-2048.pem --pad --confirm --align 4 --header-size 0x400 --pad-header --slot-size 0x200000 --version 1.0.0+1001 ota_demo.bin ota_demo.signed.bin
        - ls -l $IMAGE_PATH
- deploy:
    timeout:
      minutes: 5
    to: flasher
    images:
      image:
        url: downloads://ota_demo.signed.bin
      settings:
        url: downloads://flash.settings
      mcuboot:
        url: downloads://mcuboot_opensource.elf
- boot:
    timeout:
      minutes: 10
    method: minimal
- test:
    monitors:
    - name: "boot_test"
      start: "---------STARTING DEMO---------"
      end: "Sleeping 15 seconds"
      pattern: _unused_ 
