device_type: mimxrt1170_cm7
job_name: basic_mcu_ota_se050
timeouts:
  job:
    minutes: 15
  action:
    minutes: 5
  connection:
    minutes: 2
priority: medium
visibility: public
metadata:
  CI_TEST_1_v1001/RUNNING_FROM_SLOT=: "1"
  CI_TEST_1_v1001/CHECKIN: "successful"
  CI_TEST_2_v1002/RUNNING_FROM_SLOT=: "2"
  CI_TEST_2_v1002/CHECKIN: "successful"
  CI_TEST_3_v1003/RUNNING_FROM_SLOT=: "1"
  CI_TEST_4_v1004/ROLLBACK_TEST=: "1"
  CI_TEST_3_v1003/CHECKIN: "successful"
  CI_TEST_3_v1003/ROLLBACK: "1"
actions:
- deploy:
    namespace: cleanup
    timeout:
      minutes: 15
    to: downloads
    images:
      build:
        url: https://s.lava.infra.foundries.io/el2go_cleanup_rt1170.signed.bin
        headers:
          Authorization: LAVA_BASIC_AUTH
      mcuboot:
        url: https://s.lava.infra.foundries.io/mcuboot_opensource_rt1170.elf
        headers:
          Authorization: LAVA_BASIC_AUTH
    postprocess:
      docker:
        image: miloszwasilewski/mcu_lava:latest
        steps:
        - export IMAGE_PATH=$PWD
        - ls -l "${IMAGE_PATH}"
        - echo "DEVICE_TYPE=mimxrt1170_cm7" >> flash.settings
        - echo "TMPFILES=mcuboot_opensource_rt1170.elf" >> flash.settings
        - ls -l $IMAGE_PATH
- deploy:
    namespace: cleanup
    timeout:
      minutes: 5
    to: flasher
    images:
      image:
        url: downloads://el2go_cleanup_rt1170.signed.bin
      settings:
        url: downloads://flash.settings
      mcuboot:
        url: downloads://mcuboot_opensource_rt1170.elf
- boot:
    namespace: cleanup
    timeout:
      minutes: 10
    method: minimal
- test:
    namespace: cleanup
    monitors:
    - name: "basic_test"
      start: "---------STARTING DEMO---------"
      end: "Halting execution"
      pattern: _unused_


- deploy:
    namespace: testrun
    connection-namespace: cleanup
    timeout:
      minutes: 15
    to: downloads
    images:
      build:
        url: {BUILD_URL}
        headers:
          Authorization: GITHUB_AUTH
      mcuboot:
        url: https://s.lava.infra.foundries.io/mcuboot_opensource_rt1170.elf
        headers:
          Authorization: LAVA_BASIC_AUTH
    postprocess:
      docker:
        image: miloszwasilewski/mcu_lava:latest
        steps:
        - export IMAGE_PATH=$PWD
        - ls -l "${IMAGE_PATH}"
        - unzip "zip"
        - ls -l "${IMAGE_PATH}"
        - echo "DEVICE_TYPE=mimxrt1170_cm7" >> flash.settings
        - echo "TMPFILES=mcuboot_opensource_rt1170.elf" >> flash.settings
        - ls -l $IMAGE_PATH
- deploy:
    namespace: testrun
    connection-namespace: cleanup
    timeout:
      minutes: 5
    to: flasher
    images:
      image:
        url: downloads://ota_demo.SE05X_rt1170.1001.signed.bin
      settings:
        url: downloads://flash.settings
      mcuboot:
        url: downloads://mcuboot_opensource_rt1170.elf
- command:
    name: remove_from_factory
- command:
    name: remove_from_denied
- boot:
    namespace: testrun
    connection-namespace: cleanup
    timeout:
      minutes: 10
    method: minimal
- test:
    namespace: testrun
    connection-namespace: cleanup
    monitors:
    - name: "basic_test"
      start: "---------STARTING DEMO---------"
      end: "TEST CI_TEST_3_v1003 ROLLBACK=1"
      pattern: _unused_ 
