name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: miloszwasilewski/mcu_lava:latest
    env:
      ARMGCC_DIR: "/usr/"
      AKNANO_BOARD_MODEL: "rt1170"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./

      - name: Build
        working-directory: ./
        run: |
          west init -l .
          west update
          ln -sfn dm-ak-nano-mcuxpresso-manifest ../poc
          export MANIFEST_HASH=$(git -C ../foundriesio/aktualizr-nano/ log --format=%H -n 1)
          echo "====================================="
          echo "${MANIFEST_HASH}"
          echo "MANIFEST_HASH=${MANIFEST_HASH}" >> $GITHUB_ENV
          echo "====================================="
          cd ../foundriesio/dm-ak-nano-mcuxpresso/armgcc
          ./build_flexspi_nor_release.sh
          echo "====================================="
          echo "${GITHUB_RUN_ID}"
          echo "====================================="
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flex-nor-release
          path: /__w/dm-ak-nano-mcuxpresso-manifest/foundriesio/dm-ak-nano-mcuxpresso/armgcc/flexspi_nor_release/*
