name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        BOARD_MODEL: ["rt1170", "rt1060"]
    runs-on: ubuntu-latest
    container: miloszwasilewski/mcu_lava:latest
    env:
      ARMGCC_DIR: "/usr/"
      AKNANO_BOARD_MODEL: ${{matrix.BOARD_MODEL}}
      AKNANO_USE_MAC_ADDRESS_AS_DEVICE_UUID: 1
      AKNANO_DUMP_DOWNLOADED_TUF_METADATA: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./

      - name: West Init
        env:
          PROVISIONING_SECRET: ${{secrets.AKNANO_PROVISIONING_SECRET}}
          SECRET: ${{secrets.AKNANO_SECRET}}
        run: |
          west init -l .
          west update
          ln -sfn dm-ak-nano-mcuxpresso-manifest ../poc
          export MANIFEST_HASH=$(git -C ../foundriesio/aktualizr-nano/ log --format=%H -n 1)
          echo "====================================="
          echo "${MANIFEST_HASH}"
          echo "MANIFEST_HASH=${MANIFEST_HASH}" >> $GITHUB_ENV
          echo "====================================="
          #echo "${PROVISIONING_SECRET}" > ../foundriesio/aktualizr-nano/src/provisioning/aknano_provisioning_secret.h
          #echo "${SECRET}" > ../foundriesio/aktualizr-nano/src/aknano_secret.h

      - name: Build ci-test-1
        env:
          DEFAULT_TAG: "ci-test-1"
          AKNANO_TEST_MESSAGE_PREAMBLE: "TEST CI_TEST_1"
          ota_revision: "1001"
        working-directory: ./
        run: |
          export AKNANO_DEFAULT_TAG="${GITHUB_RUN_ID}-${DEFAULT_TAG}"
          export signed_file="flexspi_nor_release/ota_demo.${AKNANO_BOARD_MODEL}.${ota_revision}.signed.bin"
          cd ../foundriesio/dm-ak-nano-mcuxpresso/armgcc
          ./build_flexspi_nor_release.sh
          cp "flexspi_nor_release/ota_demo.bin" "flexspi_nor_release/ota_demo.${AKNANO_BOARD_MODEL}.${ota_revision}.bin"
          imgtool version
          imgtool sign --key /home/root-rsa-2048.pem --align 4 --header-size 0x400 --pad-header --slot-size 0x200000 --version 1.0.0+${ota_revision} flexspi_nor_release/ota_demo.bin ${signed_file}
          rm flexspi_nor_release/ota_demo.bin

      - name: Build ci-test-2
        env:
          DEFAULT_TAG: "ci-test-2"
          AKNANO_TEST_MESSAGE_PREAMBLE: "TEST CI_TEST_2"
          ota_revision: "1002"
        working-directory: ./
        run: |
          export AKNANO_DEFAULT_TAG="${GITHUB_RUN_ID}-${DEFAULT_TAG}"
          export signed_file="flexspi_nor_release/ota_demo.${AKNANO_BOARD_MODEL}.${ota_revision}.signed.bin"
          cd ../foundriesio/dm-ak-nano-mcuxpresso/armgcc
          ./build_flexspi_nor_release.sh
          cp "flexspi_nor_release/ota_demo.bin" "flexspi_nor_release/ota_demo.${AKNANO_BOARD_MODEL}.${ota_revision}.bin"
          imgtool version
          imgtool sign --key /home/root-rsa-2048.pem --align 4 --header-size 0x400 --pad-header --slot-size 0x200000 --version 1.0.0+${ota_revision} flexspi_nor_release/ota_demo.bin ${signed_file}
          rm flexspi_nor_release/ota_demo.bin

      - name: Build ci-test-3
        env:
          DEFAULT_TAG: "ci-test-4"
          AKNANO_TEST_MESSAGE_PREAMBLE: "TEST CI_TEST_4"
          ota_revision: "1003"
        working-directory: ./
        run: |
          export AKNANO_DEFAULT_TAG="${GITHUB_RUN_ID}-${DEFAULT_TAG}"
          export signed_file="flexspi_nor_release/ota_demo.${AKNANO_BOARD_MODEL}.${ota_revision}.signed.bin"
          cd ../foundriesio/dm-ak-nano-mcuxpresso/armgcc
          ./build_flexspi_nor_release.sh
          cp "flexspi_nor_release/ota_demo.bin" "flexspi_nor_release/ota_demo.${AKNANO_BOARD_MODEL}.${ota_revision}.bin"
          imgtool version
          imgtool sign --key /home/root-rsa-2048.pem --align 4 --header-size 0x400 --pad-header --slot-size 0x200000 --version 1.0.0+${ota_revision} flexspi_nor_release/ota_demo.bin ${signed_file}
          rm flexspi_nor_release/ota_demo.bin

      - name: Build ci-test-4
        env:
          DEFAULT_TAG: "ci-test-4"
          AKNANO_TEST_MESSAGE_PREAMBLE: "TEST CI_TEST_4"
          AKNANO_TEST_ROLLBACK: 1
          ota_revision: "1004"
        working-directory: ./
        run: |
          export AKNANO_DEFAULT_TAG="${GITHUB_RUN_ID}-${DEFAULT_TAG}"
          export signed_file="flexspi_nor_release/ota_demo.${AKNANO_BOARD_MODEL}.${ota_revision}.signed.bin"
          cd ../foundriesio/dm-ak-nano-mcuxpresso/armgcc
          ./build_flexspi_nor_release.sh
          cp "flexspi_nor_release/ota_demo.bin" "flexspi_nor_release/ota_demo.${AKNANO_BOARD_MODEL}.${ota_revision}.bin"
          imgtool version
          imgtool sign --key /home/root-rsa-2048.pem --align 4 --header-size 0x400 --pad-header --slot-size 0x200000 --version 1.0.0+${ota_revision} flexspi_nor_release/ota_demo.bin ${signed_file}
          rm flexspi_nor_release/ota_demo.bin

      - name: Create and upload Targets
        working-directory: ./
        env:
          FIOCTL_TOKEN: ${{secrets.FIOCTL_TOKEN}}
        run: |
          export BUILD_HWID="mimx${AKNANO_BOARD_MODEL}-evk"
          cd ../foundriesio/dm-ak-nano-mcuxpresso/armgcc/flexspi_nor_release
          fioctl version
          fioctl --verbose --token "${FIOCTL_TOKEN}" --factory milosz-mcu targets list --raw
          fioctl --verbose --token "${FIOCTL_TOKEN}" --factory milosz-mcu targets create-file "ota_demo.${AKNANO_BOARD_MODEL}.1002.signed.bin" "${GITHUB_RUN_ID}1002" "${BUILD_HWID}" "${GITHUB_RUN_ID}-ci-test-1"
          fioctl --verbose --token "${FIOCTL_TOKEN}" --factory milosz-mcu targets create-file "ota_demo.${AKNANO_BOARD_MODEL}.1003.signed.bin" "${GITHUB_RUN_ID}1003" "${BUILD_HWID}" "${GITHUB_RUN_ID}-ci-test-2"
          fioctl --verbose --token "${FIOCTL_TOKEN}" --factory milosz-mcu targets create-file "ota_demo.${AKNANO_BOARD_MODEL}.1004.signed.bin" "${GITHUB_RUN_ID}1004" "${BUILD_HWID}" "${GITHUB_RUN_ID}-ci-test-3"
          fioctl --verbose --token "${FIOCTL_TOKEN}" --factory milosz-mcu targets list --raw

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flex-nor-release
          path: /__w/dm-ak-nano-mcuxpresso-manifest/foundriesio/dm-ak-nano-mcuxpresso/armgcc/flexspi_nor_release/*
